=== AmberDenton/UTK_XML_Upload_flaskProject/submission.dtd
<!ELEMENT Manifest (submission)>
<!ELEMENT submission (trainingprovider)>


<!-- GENERAL INFORMATION OF TRAINING PROVIDER -->



<!ELEMENT trainingprovider (class+)>

			<!ATTLIST trainingprovider

				tpid CDATA #REQUIRED

				tpphone CDATA #REQUIRED

				tpemail CDATA #REQUIRED>



			<!-- INFORMATION OF A COURSE -->

			<!-- classtype is either Instructor led (I), Web based Domestic (WD) or Web based International (WI) -->

			<!--  depends on the classtype, different attributes are required.  Please refer to the SOP for the list of required fields -->



			<!ELEMENT class (instructorpoc*,registration?,evaluations?,testaverage?)>

			<!ATTLIST class

				catalognum CDATA #REQUIRED

				classtype (I|WD|WI) #REQUIRED

				classcity CDATA #REQUIRED

 				classstate (AL|AK|AZ|AR|CA|CO|CT|DC|DE|FL|GA|HI|Id|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|AS|FM|GU|MH|MP|PW|PR|VI|AA|AE|AP) #REQUIRED

 				classzipcode CDATA #IMPLIED

 				classcountry CDATA #IMPLIED

 				startdate CDATA #REQUIRED

 				enddate CDATA #REQUIRED

				starttime CDATA #IMPLIED

				endtime CDATA #IMPLIED

 				numstudent CDATA #REQUIRED

 				trainingmethod CDATA #REQUIRED

 				contacthours CDATA #IMPLIED

 				preparerlastname CDATA #IMPLIED

 				preparerfirstname CDATA #IMPLIED

 				batchpreparerphone CDATA #IMPLIED

 				batchprepareremail CDATA #IMPLIED>



				<!-- INFORMATION OF THE CLASS INSTRUCTOR -->

				<!-- The following portion contains the information the lead instructor of the class -->

				<!-- This portion is only required if the classtype is Instructor led -->



				<!ELEMENT instructorpoc EMPTY>

				<!ATTLIST instructorpoc

  						instlastname CDATA #REQUIRED

  						instfirstname CDATA #REQUIRED

  						instphone CDATA #REQUIRED

  						instemail CDATA #IMPLIED>



				<!-- LIST OF STUDENTS AND THEIR INFORMATION -->

				<!-- Student can either be a domestic student or an international student. -->

				<!-- If domestic student, international attribute must be "N".  -->

				<!-- If international student, international attribute must be "Y". -->



				<!ELEMENT registration (student+)>

					<!ELEMENT student EMPTY>

					<!ATTLIST student

						sid CDATA #IMPLIED

						international (Y|N) #REQUIRED

  						studentlastname CDATA #REQUIRED

  						studentfirstname CDATA #REQUIRED

  						studentmi CDATA #IMPLIED

						studentsuffix CDATA #IMPLIED

						citizen CDATA #IMPLIED

  						agency CDATA #IMPLIED

						yearsinpos CDATA #IMPLIED

  						title CDATA #IMPLIED

  						address1 CDATA #IMPLIED

  						address2 CDATA #IMPLIED

  						address3 CDATA #IMPLIED

  						studentcity CDATA #REQUIRED

  						studentzipcode CDATA #IMPLIED

  						studentstate (AL|AK|AZ|AR|CA|CO|CT|DC|DE|FL|GA|HI|Id|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|AS|FM|GU|MH|MP|PW|PR|VI|AA|AE|AP) #REQUIRED

  						studentcountry CDATA #IMPLIED

  						studentphone CDATA #REQUIRED

  						studentemail CDATA #REQUIRED

  						discipline (LE|EMS|EM|FS|HM|PW|GA|PSC|HC|PH|SR|AES|AGS|CV|TS|IT|PSP|OTH|E|SS) #REQUIRED

  						govnlevel (L|S|DF|NF|NA|T|P|FF|I|M|SD) #REQUIRED>



				<!-- EVALUATION INFORMATION OF A CLASS -->



				<!ELEMENT evaluations (evaldata*)>

					<!ATTLIST evaluations

						level CDATA #IMPLIED>

					<!ELEMENT evaldata (question+,comment*)>

						<!ATTLIST evaldata

							 dscplncode (LE|EMS|EM|FS|HM|PW|GA|PSC|HC|PH|SR|AES|AGS|CV|TS|IT|PSP|OTH|E|SS) #IMPLIED

							 yearsofexpcode (1|2|3|4|5|6|7) #IMPLIED

							 supervisor (Y|N) #IMPLIED

							 knwllvlcode (N|B|INT|E) #IMPLIED

							 primaryafflcode (F|S|C|CT|T|PS|SD|OTH) #IMPLIED

							 populationcode (1|2|3|4|5|6) #IMPLIED>

							<!ELEMENT question EMPTY>

							<!ATTLIST question

                answer (0|1|2|3|4|5|6|7|8|9|10) #REQUIRED

                id (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23) #REQUIRED>

							<!ELEMENT comment EMPTY>

							<!ATTLIST comment

                answer CDATA #REQUIRED

                id (24|25|26|27) #REQUIRED>



<!-- PRE/POST TEST AVERAGES INFORMATION OF A CLASS -->



				<!ELEMENT testaverage EMPTY>

				<!ATTLIST testaverage

					pretest CDATA #REQUIRED

					posttest CDATA #REQUIRED>

=== AmberDenton/UTK_XML_Upload_flaskProject/Harris_County_MGT489.xml
<?xml version="1.0" ?>
<!DOCTYPE Manifest SYSTEM "submission.dtd">
<Manifest>
    <submission>
        <trainingprovider tpemail="cafspoperations@utk.edu" tpid="UT-CVM" tpphone="8659740757">
            <class catalognum="MGT-489" classtype="I" classcity="Houston" classstate="TX" classzipcode="77024" startdate="7252023" enddate="7262023" numstudent="9" trainingmethod="M">
                <instructorpoc instlastname="Palumbo-Miele" instfirstname="Donna" instphone="3213324048" instemail="donna@concordiasupplychain.com"/>
                <instructorpoc instlastname="Miller" instfirstname="Steven" instphone="8659746530" instemail="steve@londonpacket.com"/>
                <registration>
                    <student sid="5119373" studentlastname="Fawcett" studentfirstname="Ronald" international="N" studentcity="Sugar Land" studentstate="TX" studentzipcode="77498" studentemail="ronald.fawcett@fortbendcountytx.gov" studentphone="2819808685" govnlevel="L" discipline="EM"/>
                    <student sid="6159063" studentlastname="Hannan" studentfirstname="James" international="N" studentcity="Kingwood" studentstate="TX" studentzipcode="77345" studentemail="jamie.hannan@oem.hctx.net" studentphone="2817990320" govnlevel="L" discipline="EM"/>
                    <student sid="4568419" studentlastname="Jimenez" studentfirstname="Casey" international="N" studentcity="Bedford" studentstate="TX" studentzipcode="76022" studentemail="casey.account@yahoo.com" studentphone="8176823349" govnlevel="L" discipline="EM"/>
                    <student sid="588939" studentlastname="menke" studentfirstname="mardie" international="N" studentcity="Houston" studentstate="TX" studentzipcode="77024" studentemail="mardie.menke@oem.hctx.net" studentphone="7134269539" govnlevel="L" discipline="EM"/>
                    <student sid="5510706" studentlastname="Pastrano" studentfirstname="Thomas" international="N" studentcity="Tomball" studentstate="TX" studentzipcode="77377" studentemail="thomas.pastrano@houstontx.gov" studentphone="2812579291" govnlevel="L" discipline="EM"/>
                    <student sid="610409" studentlastname="Shryock" studentfirstname="Brett" international="N" studentcity="Houston" studentstate="TX" studentzipcode="77024" studentemail="brett.shryock@oem.hctx.net" studentphone="3614011266" govnlevel="L" discipline="EM"/>
                    <student sid="4175363" studentlastname="Stevenson" studentfirstname="Keyona" international="N" studentcity="Houston" studentstate="TX" studentzipcode="77024" studentemail="Keyona.stevenson@oem.hctx.net" studentphone="7138813100" govnlevel="L" discipline="EM"/>
                    <student sid="303930" studentlastname="suter" studentfirstname="Jennifer" international="N" studentcity="Houston" studentstate="TX" studentzipcode="77024" studentemail="jennifer.suter@att.net" studentphone="7134269544" govnlevel="L" discipline="EM"/>
                    <student sid="893859" studentlastname="Vargas" studentfirstname="Cynthia" international="N" studentcity="Rosharon" studentstate="TX" studentzipcode="77583" studentemail="vargasc@uhd.edu" studentphone="8326511466" govnlevel="NA" discipline="EM"/>
                </registration>
                <evaluations>
                    <evaldata>
                        <question answer="3" id="1"/>
                        <question answer="4" id="2"/>
                        <question answer="4" id="3"/>
                        <question answer="5" id="4"/>
                        <question answer="5" id="5"/>
                        <question answer="5" id="6"/>
                        <question answer="0" id="7"/>
                        <question answer="0" id="8"/>
                        <question answer="0" id="9"/>
                        <question answer="0" id="10"/>
                        <question answer="0" id="11"/>
                        <question answer="0" id="12"/>
                        <question answer="0" id="13"/>
                        <question answer="0" id="14"/>
                        <question answer="4" id="15"/>
                        <question answer="4" id="16"/>
                        <question answer="0" id="17"/>
                        <question answer="4" id="18"/>
                        <question answer="4" id="19"/>
                        <question answer="4" id="20"/>
                        <question answer="4" id="21"/>
                        <question answer="4" id="22"/>
                        <question answer="4" id="23"/>
                        <comment answer="nan" id="24"/>
                        <comment answer="nan" id="25"/>
                        <comment answer="nan" id="26"/>
                        <comment answer="nan" id="27"/>
                    </evaldata>
                    <evaldata>
                        <question answer="3" id="1"/>
                        <question answer="4" id="2"/>
                        <question answer="4" id="3"/>
                        <question answer="4" id="4"/>
                        <question answer="2" id="5"/>
                        <question answer="4" id="6"/>
                        <question answer="5" id="7"/>
                        <question answer="5" id="8"/>
                        <question answer="5" id="9"/>
                        <question answer="5" id="10"/>
                        <question answer="5" id="11"/>
                        <question answer="5" id="12"/>
                        <question answer="4" id="13"/>
                        <question answer="5" id="14"/>
                        <question answer="4" id="15"/>
                        <question answer="4" id="16"/>
                        <question answer="4" id="17"/>
                        <question answer="4" id="18"/>
                        <question answer="4" id="19"/>
                        <question answer="5" id="20"/>
                        <question answer="5" id="21"/>
                        <question answer="5" id="22"/>
                        <question answer="5" id="23"/>
                        <comment answer="The subject matter in general was new to me so the whole course was valuable. I think the models explaining supply chains and identifying issues utilizing maps and GIS were most helpful" id="24"/>
                        <comment answer="There were too many activities or too much time allocated for them. I found myself losing interest with the amount of time given." id="25"/>
                        <comment answer="I am interested in finding more supply chain and critical infrastructure trainings." id="26"/>
                        <comment answer="Mainly reducing the number of activities or time allocated for them." id="27"/>
                    </evaldata>
                    <evaldata>
                        <question answer="2" id="1"/>
                        <question answer="4" id="2"/>
                        <question answer="5" id="3"/>
                        <question answer="5" id="4"/>
                        <question answer="5" id="5"/>
                        <question answer="5" id="6"/>
                        <question answer="5" id="7"/>
                        <question answer="5" id="8"/>
                        <question answer="5" id="9"/>
                        <question answer="5" id="10"/>
                        <question answer="5" id="11"/>
                        <question answer="5" id="12"/>
                        <question answer="5" id="13"/>
                        <question answer="5" id="14"/>
                        <question answer="5" id="15"/>
                        <question answer="5" id="16"/>
                        <question answer="5" id="17"/>
                        <question answer="5" id="18"/>
                        <question answer="5" id="19"/>
                        <question answer="5" id="20"/>
                        <question answer="5" id="21"/>
                        <question answer="5" id="22"/>
                        <question answer="5" id="23"/>
                        <comment answer="Hands on use of the RAPT tool" id="24"/>
                        <comment answer="Too many class activities were tiring" id="25"/>
                        <comment answer="O-305" id="26"/>
                        <comment answer="Cut the group activities in half.  Midway through the second day I felt mentally exhausted and was just going through the motions." id="27"/>
                    </evaldata>
                    <evaldata>
                        <question answer="2" id="1"/>
                        <question answer="3" id="2"/>
                        <question answer="5" id="3"/>
                        <question answer="5" id="4"/>
                        <question answer="5" id="5"/>
                        <question answer="5" id="6"/>
                        <question answer="5" id="7"/>
                        <question answer="5" id="8"/>
                        <question answer="5" id="9"/>
                        <question answer="5" id="10"/>
                        <question answer="5" id="11"/>
                        <question answer="5" id="12"/>
                        <question answer="5" id="13"/>
                        <question answer="5" id="14"/>
                        <question answer="4" id="15"/>
                        <question answer="5" id="16"/>
                        <question answer="5" id="17"/>
                        <question answer="4" id="18"/>
                        <question answer="4" id="19"/>
                        <question answer="5" id="20"/>
                        <question answer="5" id="21"/>
                        <question answer="5" id="22"/>
                        <question answer="5" id="23"/>
                        <comment answer="The activities were of a great value in being able to think and work through processes." id="24"/>
                        <comment answer="Nothing." id="25"/>
